version: "3.7"

services:
  rental-up:
    container_name: rental-up
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/src"
      - /src/node_modules
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    command: npm start
    environment:
      - NODE_ENV=development
